apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec-r1
spec:
  # Add fields here
  nodes: 3
  # uiServiceType: LoadBalancer
  license: |
    ----- LICENSE START -----
    J8MF4ore5gkvhXq5oobQnFfgaFjj64irbqiOrE333fGaPPt1r/XQ9lOUVSYz
    njyXmWBdeNjjvFyImCp6ElrhYIY+Sg+ItSeUqaCaWNNY0idgUgWJ4PDaSuZx
    2FEC2MP6DuvIyj/+Wj7Snzzn9gE1embGknvJp5htZD9U3sM+nMiVw9uExZ3N
    pPElgZfq4CNKeWhy4+5E2XVRfsFVA8vXxxLpnImgS7bMcMxdCKtPit03x9l5
    i42NBN+udpRFu7Lxg2Sq7tlaz81TJP7qaEPi7peIvoYqABhOsJcSBO2HzuAk
    I6/EGD8PJ4bE7s6D8MJ7HU/gXbPMe/f580Uxfcorbw==
    ----- LICENSE END -----
spec:
  activeActive:
    apiIngressUrl: api.r1.34.152.11.67.nip.io
    dbIngressSuffix: -db.r1.34.152.11.67.nip.io
    ingressAnnotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    method: ingress
