#!/bin/bash

LOCS="$(cat loc-list)" 
[[ $1 = "" ]] || LOCS=$1

declare -A  IP U P FQDN URL INGRESS_DB_SUFFIX REPL_EP REPL_TLS_SNI

for LOC in $LOCS; do
	. ./set-site-parameters $LOC >/dev/null 2>&1
	
	U[$LOC]=$(kubectl get secret rec-$SITE -o jsonpath='{.data.username}' | base64 --decode)
	P[$LOC]=$(kubectl get secret rec-$SITE -o jsonpath='{.data.password}' | base64 --decode)

	UI_IP=$(kubectl get service/rec-$SITE-ui -o yaml | grep ip: | awk '{print $NF}')
	UI_PORT=$(kubectl get service/rec-$SITE-ui -o yaml | grep port: | awk '{print $NF}')
	echo "UI is at:  https://$UI_IP:$UI_PORT    User= ${U[$LOC]}   Password= ${P[$LOC]}"
done

