apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: redb-admission
webhooks:
- name: redb.admission.redislabs
  failurePolicy: Fail
  rules:
  - apiGroups:   ["app.redislabs.com"]
    apiVersions: ["v1alpha1"]
    operations:  ["*"]
    resources:   ["redisenterprisedatabases"]
  clientConfig:
    service:
      namespace: NAMESPACE_OF_SERVICE_ACCOUNT
      name: admission
      path: /admission
    caBundle: "" # Fill in with BASE64 encoded signed cert
  admissionReviewVersions: ["v1beta1"]
